football:
    league:
        action:
            countries: get_countries
            leagues: get_leagues
            standings: get_standings
        api: 9bb66184e0c8145384fd2cc0f7b914ada57b4e8fd2e4d6d586adcc27c257a978
        base:
            url: https://apiv3.apifootball.com/
rest:
    client:
        connect:
            timeout: 3000
        read:
            timeout: 5000
server:
    port: 8080
